version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"
    networks:
      - loadbalance_net

  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"
    networks:
      - loadbalance_net 

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"
    networks:
      - loadbalance_net
  
  # Can comment out the nginx container if we are using our own local installation of nginx
  nginx:
    build: ./nginx-docker
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - loadbalance_net
    depends_on:
      - app1
      - app2
      - app3
  
networks:
  loadbalance_net:
